#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# DWM Commands

# DWM Status
~/dwm-bar/dwm_bar.sh &

# Compositor
picom -f &

# Wallpaper
feh --bg-fill $HOME/Pictures/Wallpapers/anime-girl-rain-umbrella-o0.jpg
#nitrogen --restore &

# Touchpad config
xinput --set-prop "DLL096D:01 06CB:CDE6 Touchpad" "Synaptics Tap Time" 0
xinput --set-prop "DLL096D:01 06CB:CDE6 Touchpad" "Synaptics Palm Detection" 1

# Notification daemon
dunst &

# Loop
while true; do
    dwm >/dev/null 2>&1
done

# Execute DWM
exec dwm
